import { Component, OnInit } from '@angular/core';
import { FormControl, Validators } from '@angular/forms';
import { Router } from '@angular/router';
@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
})
export class NavbarComponent implements OnInit {
  recipeInp = new FormControl(null, [Validators.required]);

  constructor(private _Router: Router) {}

  ngOnInit(): void {}
  updateRecipe() {
    this._Router.navigate(['/recipes', this.recipeInp.value]);
  }
  clickNav() {
    const nav = document.getElementById('navbarSupportedContent');
    nav?.classList.remove('show');
  }
  select: Array<any> = [
    'carrot',
    'broccoli',
    'asparagus',
    'cauliflower',
    'corn',
    'cucumber',
    'green pepper',
    'lettuce',
    'mushrooms',
    'onion',
    'potato',
    'pumpkin',
    'red pepper',
    'tomato',
    'beetroot',
    'brussel sprouts',
    'peas',
    'zucchini',
    'radish',
    'sweet potato',
    'artichoke',
    'leek',
    'cabbage',
    'celery',
    'chili',
    'garlic',
    'basil',
    'coriander',
    'parsley',
    'dill',
    'rosemary',
    'oregano',
    'cinnamon',
    'saffron',
    'green bean',
    'bean',
    'chickpea',
    'lentil',
    'apple',
    'apricot',
    'avocado',
    'banana',
    'blackberry',
    'blackcurrant',
    'blueberry',
    'boysenberry',
    'cherry',
    'coconut',
    'fig',
    'grape',
    'grapefruit',
    'kiwifruit',
    'lemon',
    'lime',
    'lychee',
    'mandarin',
    'mango',
    'melon',
    'nectarine',
    'orange',
    'papaya',
    'passion fruit',
    'peach',
    'pear',
    'pineapple',
    'plum',
    'pomegranate',
    'quince',
    'raspberry',
    'strawberry',
    'watermelon',
    'salad',
    'pizza',
    'pasta',
    'popcorn',
    'lobster',
    'steak',
    'bbq',
    'pudding',
    'hamburger',
    'pie',
    'cake',
    'sausage',
    'tacos',
    'kebab',
    'poutine',
    'seafood',
    'chips',
    'fries',
    'masala',
    'paella',
    'som tam',
    'chicken',
    'toast',
    'marzipan',
    'tofu',
    'ketchup',
    'hummus',
    'chili',
    'maple syrup',
    'parma ham',
    'fajitas',
    'champ',
    'lasagna',
    'poke',
    'chocolate',
    'croissant',
    'arepas',
    'bunny chow',
    'pierogi',
    'donuts',
    'rendang',
    'sushi',
    'ice cream',
    'duck',
    'curry',
    'beef',
    'goat',
    'lamb',
    'turkey',
    'pork',
    'fish',
    'crab',
    'bacon',
    'ham',
    'pepperoni',
    'salami',
    'ribs',
  ].sort();
}
